# Generated by Django 5.1.6 on 2025-02-25 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_association'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Association',
        ),
    ]
